"use client"; // Enables state & interactivity

import { useState } from "react";
import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  function handleSidebar() {
    setSidebarOpen(!sidebarOpen);
  }
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Icons+Round"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Icons+Two+Tone"
        />
      </head>
      <body className={inter.className}>
        <Nav />

        <div
          onClick={handleSidebar}
          className="grid grid-cols-8 md:mt-12  gap-2 h-screen"
        >
          {/* Fixed Sidebar Button */}

          <span
            className="material-icons col-span-1 left-5 cursor-pointer pl-6"
            style={{ fontSize: "2rem" }}
          >
            menu
          </span>

          <div
            className={`fixed w-full h-full top-0 left-0 bg-black bg-opacity-50 z-20 cursor-pointer flex items-center ${
              sidebarOpen ? "block" : "hidden"
            }`}
          >
            <div className="transform translate-y-24 custom-width rounded-lg h-40 bg-white flex flex-col custom-height ml-8">
              <div className="flex flex-col p-3 justify-center items-center space-y-8">
                <div className="pt-10 space-y-2">
                  <img
                    src="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
                    alt=""
                    className="rounded-full h-24 object-cover w-24 "
                  />
                  <h1 className="text-lg font-bold">Dubem Ernest</h1>
                </div>
                <div className="flex flex-col gap-2">
                  <Link href="profile">
                    {" "}
                    <span className="material-icons-round">grid_view</span>
                    Dashboard
                  </Link>
                  <Link href="profile">
                    <span className="material-icons-outlined">
                      manage_accounts
                    </span>
                    My Profile
                  </Link>
                  <Link href="profile">
                    {" "}
                    <span className="material-icons-outlined">favorite</span>
                    Favourite
                  </Link>
                  <Link href="profile">
                    {" "}
                    <span className="material-icons-two-tone">diversity_1</span>
                    My Mutuals
                  </Link>
                  <Link href="profile" className="space-x-4">
                    <i className="material-icons">
                      <h2>subscriptions</h2>
                    </i>{" "}
                    My Suscribed
                  </Link>
                  <Link href="profile">Interested in me</Link>
                  <Link href="profile">
                    <span class="material-icons-outlined">manage_accounts</span>
                    <span>Settings</span>
                  </Link>
                  <Link href="profile"><span>LogOut</span> </Link>
                </div>
              </div>
            </div>
          </div>

          {/* Dynamic Page Content */}
          <main className=" col-span-7 bg-green">{children}</main>
        </div>
      </body>
    </html>
  );
}
